increase version

diff --git a/.github/workflows/publisher_npm.yml b/.github/workflows/publisher_npm.yml
--- a/.github/workflows/publisher_npm.yml
+++ b/.github/workflows/publisher_npm.yml
@@ -39,7 +39,7 @@ jobs:
       - name: Publish to npm
         run: |
           OTP=${{ github.event.inputs.otp }}
-          bun run npm publish --access public --verbose --otp $OTP || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)
+          bun run npm publish --access public --verbose --otp $OTP . || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)
 
       - name: Install and build
         run: |
