fix install and build

diff --git a/.github/workflows/publisher_npm.yml b/.github/workflows/publisher_npm.yml
--- a/.github/workflows/publisher_npm.yml
+++ b/.github/workflows/publisher_npm.yml
@@ -29,6 +29,8 @@ jobs:
             echo "NPM_TOKEN is empty. Exiting."
             exit 1
           fi
+          bun run npm config set registry https://registry.npmjs.org/
+          bun run npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
           echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
 
       - name: Install and build
@@ -42,4 +44,4 @@ jobs:
 
       - name: Publish to npm
         run: |
-          bun run npm publish --access public || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)
+          bun run npm publish --access public . || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)
