add OTP

diff --git a/.github/workflows/publisher_npm.yml b/.github/workflows/publisher_npm.yml
--- a/.github/workflows/publisher_npm.yml
+++ b/.github/workflows/publisher_npm.yml
@@ -31,6 +31,12 @@ jobs:
           fi
           bun run npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
 
+      - name: Publish to npm
+        run: |
+          echo "Please enter the OTP:"
+          read -r OTP
+          bun run npm publish --access public --verbose --otp $OTP || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)
+
       - name: Install and build
         run: |
           bun install
